services:  
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: ["gpu"]
            count: all
    volumes:
      - ~/.ollama:/root/.ollama
    restart: unless-stopped
    tty: true
    environment:
      - gpus=all
      - OLLAMA_HOST=0.0.0.0
      - OLLAMA_CONTEXT_LENGTH=8192
      - OLLAMA_USE_GPU=true

  open-webui:
    image: ghcr.io/open-webui/open-webui:latest
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
      - ~/src/:/src
    depends_on:
      - ollama
    ports:
      - 20080:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  open-webui: {}